DROP TABLE gatherData cascade;
DROP TABLE preliminary cascade;

CREATE TABLE gatherData (
	as_of_year VARCHAR(4),
	respondent_id VARCHAR(10),
	agency_name VARCHAR(255),
	agency_abbr VARCHAR(255),
	agency_code VARCHAR(1),
	loan_type_name VARCHAR(255),
	loan_type VARCHAR(1),
	property_type_name VARCHAR(255),
	property_type VARCHAR(1),
	loan_purpose_name VARCHAR(255),
	loan_purpose VARCHAR(1),
	owner_occupancy_name VARCHAR(255),
	owner_occupancy VARCHAR(1),
	loan_amount_000s VARCHAR(255),
	preapproval_name VARCHAR(255),
	preapproval VARCHAR(1),
	action_taken_name VARCHAR(255),
	action_taken VARCHAR(1),
	msamd_name VARCHAR(255),
	msamd VARCHAR(5),
	state_name VARCHAR(255),
	state_abbr VARCHAR(255),
	state_code VARCHAR(2),
	county_name VARCHAR(255),
	county_code VARCHAR(3),
	census_tract_number VARCHAR(7),
	applicant_ethnicity_name VARCHAR(255),
	applicant_ethnicity VARCHAR(1),
	co_applicant_ethnicity_name VARCHAR(255),
	co_applicant_ethnicity VARCHAR(1),
	applicant_race_name_1 VARCHAR(255),
	applicant_race_1 VARCHAR(1),
	applicant_race_name_2 VARCHAR(255),
	applicant_race_2 VARCHAR(1),
	applicant_race_name_3 VARCHAR(255),
	applicant_race_3 VARCHAR(1),
	applicant_race_name_4 VARCHAR(255),
	applicant_race_4 VARCHAR(1),
	applicant_race_name_5 VARCHAR(255),
	applicant_race_5 VARCHAR(1),
	co_applicant_race_name_1 VARCHAR(255),
	co_applicant_race_1 VARCHAR(1),
	co_applicant_race_name_2 VARCHAR(255),
	co_applicant_race_2 VARCHAR(1),
	co_applicant_race_name_3 VARCHAR(255),
	co_applicant_race_3 VARCHAR(1),
	co_applicant_race_name_4 VARCHAR(255),
	co_applicant_race_4 VARCHAR(1),
	co_applicant_race_name_5 VARCHAR(255),
	co_applicant_race_5 VARCHAR(1),
	applicant_sex_name VARCHAR(255),
	applicant_sex VARCHAR(1),
	co_applicant_sex_name VARCHAR(255),
	co_applicant_sex VARCHAR(1),
	applicant_income_000s VARCHAR(255),
	purchaser_type_name VARCHAR(255),
	purchaser_type VARCHAR(1),
	denial_reason_name_1 VARCHAR(255),
	denial_reason_1 VARCHAR(1),
	denial_reason_name_2 VARCHAR(255),
	denial_reason_2 VARCHAR(1),
	denial_reason_name_3 VARCHAR(255),
	denial_reason_3 VARCHAR(1),
	rate_spread VARCHAR(5),
	hoepa_status_name VARCHAR(255),
	hoepa_status VARCHAR(1),
	lien_status_name VARCHAR(255),
	lien_status VARCHAR(1),
	edit_status_name VARCHAR(255),
	edit_status VARCHAR(1),
	sequence_number VARCHAR(7),
	population VARCHAR(8),
	minority_population VARCHAR(255) NULL,
	hud_median_family_income VARCHAR(8),
	tract_to_msamd_income VARCHAR(255) NULL,
	number_of_owner_occupied_units VARCHAR(8),
	number_of_1_to_4_family_units VARCHAR(8),
	application_date_indicator VARCHAR(1)
);

\copy gatherData from '/Users/maxyanyan/Desktop/Rutgers Fall 2025/CS336/proj3/2017_nj_records.csv' DELIMITER ',' CSV HEADER;

CREATE TABLE preliminary (
	id serial PRIMARY KEY,
	as_of_year VARCHAR(4),
	respondent_id VARCHAR(10),
	agency_name VARCHAR(255),
	agency_abbr VARCHAR(255),
	agency_code VARCHAR(1),
	loan_type_name VARCHAR(255),
	loan_type VARCHAR(1),
	property_type_name VARCHAR(255),
	property_type VARCHAR(1),
	loan_purpose_name VARCHAR(255),
	loan_purpose VARCHAR(1),
	owner_occupancy_name VARCHAR(255),
	owner_occupancy VARCHAR(1),
	loan_amount_000s VARCHAR(255),
	preapproval_name VARCHAR(255),
	preapproval VARCHAR(1),
	action_taken_name VARCHAR(255),
	action_taken VARCHAR(1),
	msamd_name VARCHAR(255),
	msamd VARCHAR(5),
	state_name VARCHAR(255),
	state_abbr VARCHAR(255),
	state_code VARCHAR(2),
	county_name VARCHAR(255),
	county_code VARCHAR(3),
	census_tract_number VARCHAR(7),
	applicant_ethnicity_name VARCHAR(255),
	applicant_ethnicity VARCHAR(1),
	co_applicant_ethnicity_name VARCHAR(255),
	co_applicant_ethnicity VARCHAR(1),
	applicant_race_name_1 VARCHAR(255),
	applicant_race_1 VARCHAR(1),
	applicant_race_name_2 VARCHAR(255),
	applicant_race_2 VARCHAR(1),
	applicant_race_name_3 VARCHAR(255),
	applicant_race_3 VARCHAR(1),
	applicant_race_name_4 VARCHAR(255),
	applicant_race_4 VARCHAR(1),
	applicant_race_name_5 VARCHAR(255),
	applicant_race_5 VARCHAR(1),
	co_applicant_race_name_1 VARCHAR(255),
	co_applicant_race_1 VARCHAR(1),
	co_applicant_race_name_2 VARCHAR(255),
	co_applicant_race_2 VARCHAR(1),
	co_applicant_race_name_3 VARCHAR(255),
	co_applicant_race_3 VARCHAR(1),
	co_applicant_race_name_4 VARCHAR(255),
	co_applicant_race_4 VARCHAR(1),
	co_applicant_race_name_5 VARCHAR(255),
	co_applicant_race_5 VARCHAR(1),
	applicant_sex_name VARCHAR(255),
	applicant_sex VARCHAR(1),
	co_applicant_sex_name VARCHAR(255),
	co_applicant_sex VARCHAR(1),
	applicant_income_000s VARCHAR(255),
	purchaser_type_name VARCHAR(255),
	purchaser_type VARCHAR(1),
	denial_reason_name_1 VARCHAR(255),
	denial_reason_1 VARCHAR(1),
	denial_reason_name_2 VARCHAR(255),
	denial_reason_2 VARCHAR(1),
	denial_reason_name_3 VARCHAR(255),
	denial_reason_3 VARCHAR(1),
	rate_spread VARCHAR(5),
	hoepa_status_name VARCHAR(255),
	hoepa_status VARCHAR(1),
	lien_status_name VARCHAR(255),
	lien_status VARCHAR(1),
	edit_status_name VARCHAR(255),
	edit_status VARCHAR(1),
	sequence_number VARCHAR(7),
	population VARCHAR(8),
	minority_population VARCHAR(255) NULL,
	hud_median_family_income VARCHAR(8),
	tract_to_msamd_income VARCHAR(255) NULL,
	number_of_owner_occupied_units VARCHAR(8),
	number_of_1_to_4_family_units VARCHAR(8),
	application_date_indicator VARCHAR(1)
);

insert into preliminary(as_of_year,respondent_id,agency_name,agency_abbr,agency_code,loan_type_name,loan_type,property_type_name,property_type,loan_purpose_name,loan_purpose,owner_occupancy_name,owner_occupancy,loan_amount_000s,preapproval_name,preapproval,action_taken_name,action_taken,msamd_name,msamd,state_name,state_abbr,state_code,county_name,county_code,census_tract_number,applicant_ethnicity_name,applicant_ethnicity,co_applicant_ethnicity_name,co_applicant_ethnicity,applicant_race_name_1,applicant_race_1,applicant_race_name_2,applicant_race_2,applicant_race_name_3,applicant_race_3,applicant_race_name_4,applicant_race_4,applicant_race_name_5,applicant_race_5,co_applicant_race_name_1,co_applicant_race_1,co_applicant_race_name_2,co_applicant_race_2,co_applicant_race_name_3,co_applicant_race_3,co_applicant_race_name_4,co_applicant_race_4,co_applicant_race_name_5,co_applicant_race_5,applicant_sex_name,applicant_sex,co_applicant_sex_name,co_applicant_sex,applicant_income_000s,purchaser_type_name,purchaser_type,denial_reason_name_1,denial_reason_1,denial_reason_name_2,denial_reason_2,denial_reason_name_3,denial_reason_3,rate_spread,hoepa_status_name,hoepa_status,lien_status_name,lien_status,edit_status_name,edit_status,sequence_number,population,minority_population,hud_median_family_income,tract_to_msamd_income,number_of_owner_occupied_units,number_of_1_to_4_family_units,application_date_indicator)
select as_of_year,respondent_id,agency_name,agency_abbr,agency_code,loan_type_name,loan_type,property_type_name,property_type,loan_purpose_name,loan_purpose,owner_occupancy_name,owner_occupancy,loan_amount_000s,preapproval_name,preapproval,action_taken_name,action_taken,msamd_name,msamd,state_name,state_abbr,state_code,county_name,county_code,census_tract_number,applicant_ethnicity_name,applicant_ethnicity,co_applicant_ethnicity_name,co_applicant_ethnicity,applicant_race_name_1,applicant_race_1,applicant_race_name_2,applicant_race_2,applicant_race_name_3,applicant_race_3,applicant_race_name_4,applicant_race_4,applicant_race_name_5,applicant_race_5,co_applicant_race_name_1,co_applicant_race_1,co_applicant_race_name_2,co_applicant_race_2,co_applicant_race_name_3,co_applicant_race_3,co_applicant_race_name_4,co_applicant_race_4,co_applicant_race_name_5,co_applicant_race_5,applicant_sex_name,applicant_sex,co_applicant_sex_name,co_applicant_sex,applicant_income_000s,purchaser_type_name,purchaser_type,denial_reason_name_1,denial_reason_1,denial_reason_name_2,denial_reason_2,denial_reason_name_3,denial_reason_3,rate_spread,hoepa_status_name,hoepa_status,lien_status_name,lien_status,edit_status_name,edit_status,sequence_number,population,minority_population,hud_median_family_income,tract_to_msamd_income,number_of_owner_occupied_units,number_of_1_to_4_family_units,application_date_indicator from gatherData;

DROP TABLE gatherData;
